server:
  port: 8001


spring:
  #  配置微服务的名字
  application:
    name: microserviceloud-dept
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cloudDB01?useSSL=false
    #    url: jdbc:mysql://59.110.214.2:3307/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.wfy.springcloud.entities


